import { codeToHtml } from 'shiki';
import { writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// Go up from scripts/ to web package root
const outputPath = resolve(__dirname, '..', 'home-code-blocks.ts');

const installCode = await codeToHtml('npx @nilejs/cli new my-app', {
  lang: 'bash',
  theme: 'material-theme-ocean',
});

const actionCode = await codeToHtml(`// services/tasks/create.ts
import { Ok } from "slang-ts";
import { createAction, type ActionHandler } from "@nilejs/nile";
import { z } from "zod";

const createTaskSchema = z.object({
  title: z.string().min(1),
  status: z.enum(["pending", "in-progress", "done"]).default("pending"),
});

type CreateTaskPayload = z.infer<typeof createTaskSchema>;

const handler: ActionHandler<CreateTaskPayload> = (data) => {
  const task = { id: crypto.randomUUID(), ...data };
  return Ok({ task });
};

export const createTask = createAction({
  name: "create",
  description: "Create a new task",
  handler,
  validation: createTaskSchema,
});`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const serviceCode = await codeToHtml(`// services/tasks.ts
import { createService } from "@nilejs/nile";
import { createTask } from "./tasks/create";

export const tasksService = createService({
  name: "tasks",
  description: "Task management operations",
  actions: [createTask],
});`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const serverCode = await codeToHtml(`// server.ts
import { createNileServer } from "@nilejs/nile";
import { tasksService } from "./services/tasks";

const server = await createNileServer({
  serverName: "my-app",
  services: [tasksService],
  rest: {
    baseUrl: "/api",
    port: 8000,
    allowedOrigins: ["http://localhost:8000"],
  },
});

if (server.rest) {
  const { fetch } = server.rest.app;
  Bun.serve({ fetch, port: 8000 });
}`, {
  lang: 'typescript',
  theme: 'material-theme-ocean',
});

const invokeCode = await codeToHtml(`curl -X POST http://localhost:8000/api/services \\
  -H "Content-Type: application/json" \\
  -d '{
    "intent": "execute",
    "service": "tasks",
    "action": "create",
    "payload": { "title": "Ship Nile", "status": "in-progress" }
  }'`, {
  lang: 'bash',
  theme: 'material-theme-ocean',
});

// Also export the raw strings for copy buttons
const installRaw = 'npx @nilejs/cli new my-app';
const actionRaw = `// services/tasks/create.ts
import { Ok } from "slang-ts";
import { createAction, type ActionHandler } from "@nilejs/nile";
import { z } from "zod";

const createTaskSchema = z.object({
  title: z.string().min(1),
  status: z.enum(["pending", "in-progress", "done"]).default("pending"),
});

type CreateTaskPayload = z.infer<typeof createTaskSchema>;

const handler: ActionHandler<CreateTaskPayload> = (data) => {
  const task = { id: crypto.randomUUID(), ...data };
  return Ok({ task });
};

export const createTask = createAction({
  name: "create",
  description: "Create a new task",
  handler,
  validation: createTaskSchema,
});`;

const serviceRaw = `// services/tasks.ts
import { createService } from "@nilejs/nile";
import { createTask } from "./tasks/create";

export const tasksService = createService({
  name: "tasks",
  description: "Task management operations",
  actions: [createTask],
});`;

const serverRaw = `// server.ts
import { createNileServer } from "@nilejs/nile";
import { tasksService } from "./services/tasks";

const server = await createNileServer({
  serverName: "my-app",
  services: [tasksService],
  rest: {
    baseUrl: "/api",
    port: 8000,
    allowedOrigins: ["http://localhost:8000"],
  },
});

if (server.rest) {
  const { fetch } = server.rest.app;
  Bun.serve({ fetch, port: 8000 });
}`;

const invokeRaw = `curl -X POST http://localhost:8000/api/services \\
  -H "Content-Type: application/json" \\
  -d '{
    "intent": "execute",
    "service": "tasks",
    "action": "create",
    "payload": { "title": "Ship Nile", "status": "in-progress" }
  }'`;

const content = `// Auto-generated by scripts/generate-home-code.ts
// Do not edit manually

export const installCode = ${JSON.stringify(installCode)};
export const actionCode = ${JSON.stringify(actionCode)};
export const serviceCode = ${JSON.stringify(serviceCode)};
export const serverCode = ${JSON.stringify(serverCode)};
export const invokeCode = ${JSON.stringify(invokeCode)};

export const installRaw = ${JSON.stringify(installRaw)};
export const actionRaw = ${JSON.stringify(actionRaw)};
export const serviceRaw = ${JSON.stringify(serviceRaw)};
export const serverRaw = ${JSON.stringify(serverRaw)};
export const invokeRaw = ${JSON.stringify(invokeRaw)};
`;

await writeFile(outputPath, content);
console.log('Generated home code blocks at', outputPath);